ALTER TABLE biz_job_posting
    CHANGE COLUMN job_id_source url_obj_id VARCHAR(100) NULL COMMENT '招聘记录唯一标识',
    CHANGE COLUMN source_url url VARCHAR(500) NULL COMMENT '招聘职位原始链接',
    CHANGE COLUMN city job_city VARCHAR(100) NULL COMMENT '工作所在城市',
    CHANGE COLUMN industry_name job_classification VARCHAR(100) NULL COMMENT '职位所属分类',
    CHANGE COLUMN education education_need VARCHAR(50) NULL COMMENT '要求的学历水平',
    CHANGE COLUMN experience experience_year VARCHAR(50) NULL COMMENT '要求的工作经验年限',
    CHANGE COLUMN salary_text salary_raw VARCHAR(100) NULL COMMENT '原始展示的薪资范围文本',
    CHANGE COLUMN description position_info TEXT NULL COMMENT '职位详细描述，包括岗位职责和任职要求',
    CHANGE COLUMN job_benefits job_welfare TEXT NULL COMMENT '职位福利待遇',
    ADD COLUMN job_labels JSON NULL COMMENT '职位相关标签（如技能、行业方向）' AFTER job_welfare,
    ADD COLUMN company_size VARCHAR(50) NULL COMMENT '公司规模（人数范围）' AFTER company_name,
    ADD COLUMN company_finance VARCHAR(50) NULL COMMENT '公司融资阶段' AFTER company_size,
    ADD COLUMN crawl_update_time DATETIME NULL COMMENT '数据最后更新时间' AFTER crawl_time,
    DROP COLUMN company_id,
    DROP COLUMN region,
    DROP COLUMN district,
    DROP COLUMN industry_id,
    DROP COLUMN salary_unit,
    DROP COLUMN employment_type,
    DROP COLUMN requirements,
    DROP COLUMN source_site,
    DROP COLUMN data_quality,
    DROP COLUMN is_active,
    DROP COLUMN created_at,
    DROP COLUMN updated_at;

ALTER TABLE biz_job_posting
    DROP INDEX uk_source_job,
    ADD UNIQUE KEY uk_url_obj_id (url_obj_id),
    DROP INDEX idx_city,
    ADD INDEX idx_city (job_city),
    DROP INDEX idx_industry,
    ADD INDEX idx_classification (job_classification),
    DROP INDEX idx_education,
    ADD INDEX idx_education (education_need),
    DROP INDEX ft_description,
    ADD FULLTEXT INDEX ft_position_info (position_info);
