USE career_platform;

INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NORTH', '华北', 1, NULL, '华北', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NORTHEAST', '东北', 1, NULL, '东北', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-EAST', '华东', 1, NULL, '华东', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-CENTRAL', '华中', 1, NULL, '华中', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SOUTH', '华南', 1, NULL, '华南', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SOUTHWEST', '西南', 1, NULL, '西南', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NORTHWEST', '西北', 1, NULL, '西北', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HKMO', '港澳台', 1, NULL, '港澳台', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-OVERSEAS', '海外', 1, NULL, '海外', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NATIONAL', '全国', 1, NULL, '全国', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-OTHER', '其他', 1, NULL, '其他', 0, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=1, parent_code=NULL, full_name=VALUES(full_name), updated_at=NOW();

INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-BJ', '北京', 2, 'CN-NORTH', '华北/北京', 1, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-TJ', '天津', 2, 'CN-NORTH', '华北/天津', 2, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HE', '河北省', 2, 'CN-NORTH', '华北/河北省', 3, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SX', '山西省', 2, 'CN-NORTH', '华北/山西省', 4, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NM', '内蒙古自治区', 2, 'CN-NORTH', '华北/内蒙古自治区', 5, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-LN', '辽宁省', 2, 'CN-NORTHEAST', '东北/辽宁省', 6, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-JL', '吉林省', 2, 'CN-NORTHEAST', '东北/吉林省', 7, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HLJ', '黑龙江省', 2, 'CN-NORTHEAST', '东北/黑龙江省', 8, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SH', '上海', 2, 'CN-EAST', '华东/上海', 9, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-JS', '江苏省', 2, 'CN-EAST', '华东/江苏省', 10, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-ZJ', '浙江省', 2, 'CN-EAST', '华东/浙江省', 11, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-AH', '安徽省', 2, 'CN-EAST', '华东/安徽省', 12, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-FJ', '福建省', 2, 'CN-EAST', '华东/福建省', 13, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-JX', '江西省', 2, 'CN-EAST', '华东/江西省', 14, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SD', '山东省', 2, 'CN-EAST', '华东/山东省', 15, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HA', '河南省', 2, 'CN-CENTRAL', '华中/河南省', 16, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HB', '湖北省', 2, 'CN-CENTRAL', '华中/湖北省', 17, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HN', '湖南省', 2, 'CN-CENTRAL', '华中/湖南省', 18, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-GD', '广东省', 2, 'CN-SOUTH', '华南/广东省', 19, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-GX', '广西壮族自治区', 2, 'CN-SOUTH', '华南/广西壮族自治区', 20, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HI', '海南省', 2, 'CN-SOUTH', '华南/海南省', 21, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-CQ', '重庆', 2, 'CN-SOUTHWEST', '西南/重庆', 22, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SC', '四川省', 2, 'CN-SOUTHWEST', '西南/四川省', 23, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-GZ', '贵州省', 2, 'CN-SOUTHWEST', '西南/贵州省', 24, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-YN', '云南省', 2, 'CN-SOUTHWEST', '西南/云南省', 25, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-XZ', '西藏自治区', 2, 'CN-SOUTHWEST', '西南/西藏自治区', 26, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-SN', '陕西省', 2, 'CN-NORTHWEST', '西北/陕西省', 27, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-GS', '甘肃省', 2, 'CN-NORTHWEST', '西北/甘肃省', 28, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-QH', '青海省', 2, 'CN-NORTHWEST', '西北/青海省', 29, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-NX', '宁夏回族自治区', 2, 'CN-NORTHWEST', '西北/宁夏回族自治区', 30, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-XJ', '新疆维吾尔自治区', 2, 'CN-NORTHWEST', '西北/新疆维吾尔自治区', 31, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-HK', '香港特别行政区', 2, 'CN-HKMO', '港澳台/香港特别行政区', 32, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-MO', '澳门特别行政区', 2, 'CN-HKMO', '港澳台/澳门特别行政区', 33, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-INTL', '海外', 2, 'CN-OVERSEAS', '海外/海外', 34, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-ALL', '全国', 2, 'CN-NATIONAL', '全国/全国', 35, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();
INSERT INTO dim_region (region_code, region_name, region_level, parent_code, full_name, sort_no, status, created_at, updated_at) VALUES ('CN-MISC', '其他', 2, 'CN-OTHER', '其他/其他', 36, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE region_name=VALUES(region_name), region_level=2, parent_code=VALUES(parent_code), full_name=VALUES(full_name), updated_at=NOW();

UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/七台河', updated_at = NOW() WHERE region_name = '七台河' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/万宁', updated_at = NOW() WHERE region_name = '万宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/三亚', updated_at = NOW() WHERE region_name = '三亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/三明', updated_at = NOW() WHERE region_name = '三明' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/三沙', updated_at = NOW() WHERE region_name = '三沙' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/三门峡', updated_at = NOW() WHERE region_name = '三门峡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SH', full_name = '华东/上海/上海', updated_at = NOW() WHERE region_name = '上海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/上饶', updated_at = NOW() WHERE region_name = '上饶' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/东方', updated_at = NOW() WHERE region_name = '东方' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/东莞', updated_at = NOW() WHERE region_name = '东莞' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/东营', updated_at = NOW() WHERE region_name = '东营' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NX', full_name = '西北/宁夏回族自治区/中卫', updated_at = NOW() WHERE region_name = '中卫' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/中山', updated_at = NOW() WHERE region_name = '中山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/临夏', updated_at = NOW() WHERE region_name = '临夏' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/临汾', updated_at = NOW() WHERE region_name = '临汾' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/临沂', updated_at = NOW() WHERE region_name = '临沂' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/临沧', updated_at = NOW() WHERE region_name = '临沧' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/临高', updated_at = NOW() WHERE region_name = '临高' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/丹东', updated_at = NOW() WHERE region_name = '丹东' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/丽水', updated_at = NOW() WHERE region_name = '丽水' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/丽江', updated_at = NOW() WHERE region_name = '丽江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/乌兰察布', updated_at = NOW() WHERE region_name = '乌兰察布' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/乌兹别克斯坦', updated_at = NOW() WHERE region_name = '乌兹别克斯坦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/乌干达', updated_at = NOW() WHERE region_name = '乌干达' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/乌海', updated_at = NOW() WHERE region_name = '乌海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/乌鲁木齐', updated_at = NOW() WHERE region_name = '乌鲁木齐' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/乐东', updated_at = NOW() WHERE region_name = '乐东' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/乐山', updated_at = NOW() WHERE region_name = '乐山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/九江', updated_at = NOW() WHERE region_name = '九江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/云浮', updated_at = NOW() WHERE region_name = '云浮' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/五家渠市', updated_at = NOW() WHERE region_name = '五家渠市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/五指山', updated_at = NOW() WHERE region_name = '五指山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/亳州', updated_at = NOW() WHERE region_name = '亳州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/仙桃市', updated_at = NOW() WHERE region_name = '仙桃市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/以色列', updated_at = NOW() WHERE region_name = '以色列' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/伊拉克', updated_at = NOW() WHERE region_name = '伊拉克' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/伊春', updated_at = NOW() WHERE region_name = '伊春' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/伊犁', updated_at = NOW() WHERE region_name = '伊犁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/佛山', updated_at = NOW() WHERE region_name = '佛山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/佳木斯', updated_at = NOW() WHERE region_name = '佳木斯' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/俄罗斯联邦', updated_at = NOW() WHERE region_name = '俄罗斯联邦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/保亭', updated_at = NOW() WHERE region_name = '保亭' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/保定', updated_at = NOW() WHERE region_name = '保定' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/保山', updated_at = NOW() WHERE region_name = '保山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/信阳', updated_at = NOW() WHERE region_name = '信阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/儋州', updated_at = NOW() WHERE region_name = '儋州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/克孜勒苏柯尔克孜', updated_at = NOW() WHERE region_name = '克孜勒苏柯尔克孜' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/克拉玛依', updated_at = NOW() WHERE region_name = '克拉玛依' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ALL', full_name = '全国/全国/全国', updated_at = NOW() WHERE region_name = '全国' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/六安', updated_at = NOW() WHERE region_name = '六安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/六盘水', updated_at = NOW() WHERE region_name = '六盘水' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/兰州', updated_at = NOW() WHERE region_name = '兰州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/兴安盟', updated_at = NOW() WHERE region_name = '兴安盟' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-MISC', full_name = '其他/其他/其他', updated_at = NOW() WHERE region_name = '其他' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/内江', updated_at = NOW() WHERE region_name = '内江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/凉山', updated_at = NOW() WHERE region_name = '凉山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/几内亚', updated_at = NOW() WHERE region_name = '几内亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/刚果（金）', updated_at = NOW() WHERE region_name = '刚果（金）' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/加纳', updated_at = NOW() WHERE region_name = '加纳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/加蓬', updated_at = NOW() WHERE region_name = '加蓬' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/包头', updated_at = NOW() WHERE region_name = '包头' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-BJ', full_name = '华北/北京/北京', updated_at = NOW() WHERE region_name = '北京' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/北屯市', updated_at = NOW() WHERE region_name = '北屯市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/北海', updated_at = NOW() WHERE region_name = '北海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/十堰', updated_at = NOW() WHERE region_name = '十堰' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/南京', updated_at = NOW() WHERE region_name = '南京' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/南充', updated_at = NOW() WHERE region_name = '南充' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/南宁', updated_at = NOW() WHERE region_name = '南宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/南平', updated_at = NOW() WHERE region_name = '南平' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/南昌', updated_at = NOW() WHERE region_name = '南昌' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/南通', updated_at = NOW() WHERE region_name = '南通' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/南阳', updated_at = NOW() WHERE region_name = '南阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/南非', updated_at = NOW() WHERE region_name = '南非' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/博尔塔拉', updated_at = NOW() WHERE region_name = '博尔塔拉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/博茨瓦纳', updated_at = NOW() WHERE region_name = '博茨瓦纳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/卢旺达', updated_at = NOW() WHERE region_name = '卢旺达' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/印度尼西亚', updated_at = NOW() WHERE region_name = '印度尼西亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/厦门', updated_at = NOW() WHERE region_name = '厦门' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/双河市', updated_at = NOW() WHERE region_name = '双河市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/双鸭山', updated_at = NOW() WHERE region_name = '双鸭山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/可克达拉市', updated_at = NOW() WHERE region_name = '可克达拉市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/台州', updated_at = NOW() WHERE region_name = '台州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/合肥', updated_at = NOW() WHERE region_name = '合肥' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/吉安', updated_at = NOW() WHERE region_name = '吉安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/吉尔吉斯斯坦', updated_at = NOW() WHERE region_name = '吉尔吉斯斯坦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/吉林市', updated_at = NOW() WHERE region_name = '吉林市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/吐鲁番', updated_at = NOW() WHERE region_name = '吐鲁番' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/吕梁', updated_at = NOW() WHERE region_name = '吕梁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NX', full_name = '西北/宁夏回族自治区/吴忠', updated_at = NOW() WHERE region_name = '吴忠' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/周口', updated_at = NOW() WHERE region_name = '周口' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/呼伦贝尔', updated_at = NOW() WHERE region_name = '呼伦贝尔' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/呼和浩特', updated_at = NOW() WHERE region_name = '呼和浩特' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/和田', updated_at = NOW() WHERE region_name = '和田' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/咸宁', updated_at = NOW() WHERE region_name = '咸宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/咸阳', updated_at = NOW() WHERE region_name = '咸阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/哈密', updated_at = NOW() WHERE region_name = '哈密' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/哈尔滨', updated_at = NOW() WHERE region_name = '哈尔滨' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/哈萨克斯坦', updated_at = NOW() WHERE region_name = '哈萨克斯坦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/哥伦比亚', updated_at = NOW() WHERE region_name = '哥伦比亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/唐山', updated_at = NOW() WHERE region_name = '唐山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/商丘', updated_at = NOW() WHERE region_name = '商丘' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/商洛', updated_at = NOW() WHERE region_name = '商洛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/喀什', updated_at = NOW() WHERE region_name = '喀什' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/喀麦隆', updated_at = NOW() WHERE region_name = '喀麦隆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/嘉兴', updated_at = NOW() WHERE region_name = '嘉兴' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/嘉峪关', updated_at = NOW() WHERE region_name = '嘉峪关' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/四平', updated_at = NOW() WHERE region_name = '四平' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NX', full_name = '西北/宁夏回族自治区/固原', updated_at = NOW() WHERE region_name = '固原' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/图木舒克市', updated_at = NOW() WHERE region_name = '图木舒克市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/坦桑尼亚', updated_at = NOW() WHERE region_name = '坦桑尼亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/埃塞俄比亚', updated_at = NOW() WHERE region_name = '埃塞俄比亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/塔城', updated_at = NOW() WHERE region_name = '塔城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/塞拉利昂', updated_at = NOW() WHERE region_name = '塞拉利昂' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/墨西哥', updated_at = NOW() WHERE region_name = '墨西哥' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/大兴安岭', updated_at = NOW() WHERE region_name = '大兴安岭' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/大同', updated_at = NOW() WHERE region_name = '大同' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/大庆', updated_at = NOW() WHERE region_name = '大庆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/大理', updated_at = NOW() WHERE region_name = '大理' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/大连', updated_at = NOW() WHERE region_name = '大连' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/天水', updated_at = NOW() WHERE region_name = '天水' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-TJ', full_name = '华北/天津/天津', updated_at = NOW() WHERE region_name = '天津' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/天门市', updated_at = NOW() WHERE region_name = '天门市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/太原', updated_at = NOW() WHERE region_name = '太原' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/威海', updated_at = NOW() WHERE region_name = '威海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/娄底', updated_at = NOW() WHERE region_name = '娄底' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/孝感', updated_at = NOW() WHERE region_name = '孝感' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/孟加拉国', updated_at = NOW() WHERE region_name = '孟加拉国' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/宁德', updated_at = NOW() WHERE region_name = '宁德' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/宁波', updated_at = NOW() WHERE region_name = '宁波' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/安哥拉', updated_at = NOW() WHERE region_name = '安哥拉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/安庆', updated_at = NOW() WHERE region_name = '安庆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/安康', updated_at = NOW() WHERE region_name = '安康' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/安阳', updated_at = NOW() WHERE region_name = '安阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/安顺', updated_at = NOW() WHERE region_name = '安顺' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/定安', updated_at = NOW() WHERE region_name = '定安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/定西', updated_at = NOW() WHERE region_name = '定西' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/宜宾', updated_at = NOW() WHERE region_name = '宜宾' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/宜昌', updated_at = NOW() WHERE region_name = '宜昌' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/宜春', updated_at = NOW() WHERE region_name = '宜春' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/宝鸡', updated_at = NOW() WHERE region_name = '宝鸡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/宣城', updated_at = NOW() WHERE region_name = '宣城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/宿州', updated_at = NOW() WHERE region_name = '宿州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/宿迁', updated_at = NOW() WHERE region_name = '宿迁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/尼加拉瓜', updated_at = NOW() WHERE region_name = '尼加拉瓜' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/尼日利亚', updated_at = NOW() WHERE region_name = '尼日利亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/尼日尔', updated_at = NOW() WHERE region_name = '尼日尔' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/山南', updated_at = NOW() WHERE region_name = '山南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/岳阳', updated_at = NOW() WHERE region_name = '岳阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/崇左', updated_at = NOW() WHERE region_name = '崇左' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/巴中', updated_at = NOW() WHERE region_name = '巴中' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/巴布亚新几内亚', updated_at = NOW() WHERE region_name = '巴布亚新几内亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/巴彦淖尔', updated_at = NOW() WHERE region_name = '巴彦淖尔' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/巴拿马', updated_at = NOW() WHERE region_name = '巴拿马' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/巴音郭楞', updated_at = NOW() WHERE region_name = '巴音郭楞' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/常州', updated_at = NOW() WHERE region_name = '常州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/常德', updated_at = NOW() WHERE region_name = '常德' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/平凉', updated_at = NOW() WHERE region_name = '平凉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/平顶山', updated_at = NOW() WHERE region_name = '平顶山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/广元', updated_at = NOW() WHERE region_name = '广元' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/广安', updated_at = NOW() WHERE region_name = '广安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/广州', updated_at = NOW() WHERE region_name = '广州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/广西', updated_at = NOW() WHERE region_name = '广西' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/庆阳', updated_at = NOW() WHERE region_name = '庆阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/廊坊', updated_at = NOW() WHERE region_name = '廊坊' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/延安', updated_at = NOW() WHERE region_name = '延安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/延边', updated_at = NOW() WHERE region_name = '延边' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/开封', updated_at = NOW() WHERE region_name = '开封' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/张家口', updated_at = NOW() WHERE region_name = '张家口' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/张家界', updated_at = NOW() WHERE region_name = '张家界' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/张掖', updated_at = NOW() WHERE region_name = '张掖' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/徐州', updated_at = NOW() WHERE region_name = '徐州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/德宏', updated_at = NOW() WHERE region_name = '德宏' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/德州', updated_at = NOW() WHERE region_name = '德州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/德阳', updated_at = NOW() WHERE region_name = '德阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/忻州', updated_at = NOW() WHERE region_name = '忻州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/怀化', updated_at = NOW() WHERE region_name = '怀化' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/怒江', updated_at = NOW() WHERE region_name = '怒江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/恩施', updated_at = NOW() WHERE region_name = '恩施' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/惠州', updated_at = NOW() WHERE region_name = '惠州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/成都', updated_at = NOW() WHERE region_name = '成都' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/所罗门群岛', updated_at = NOW() WHERE region_name = '所罗门群岛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/扬州', updated_at = NOW() WHERE region_name = '扬州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/承德', updated_at = NOW() WHERE region_name = '承德' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/抚州', updated_at = NOW() WHERE region_name = '抚州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/抚顺', updated_at = NOW() WHERE region_name = '抚顺' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/拉萨', updated_at = NOW() WHERE region_name = '拉萨' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/揭阳', updated_at = NOW() WHERE region_name = '揭阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/摩洛哥', updated_at = NOW() WHERE region_name = '摩洛哥' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/攀枝花', updated_at = NOW() WHERE region_name = '攀枝花' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/文山', updated_at = NOW() WHERE region_name = '文山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/文昌', updated_at = NOW() WHERE region_name = '文昌' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/新乡', updated_at = NOW() WHERE region_name = '新乡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/新余', updated_at = NOW() WHERE region_name = '新余' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/新加坡', updated_at = NOW() WHERE region_name = '新加坡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/新星市', updated_at = NOW() WHERE region_name = '新星市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/无锡', updated_at = NOW() WHERE region_name = '无锡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/日喀则', updated_at = NOW() WHERE region_name = '日喀则' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/日本', updated_at = NOW() WHERE region_name = '日本' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/日照', updated_at = NOW() WHERE region_name = '日照' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/昆明', updated_at = NOW() WHERE region_name = '昆明' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/昆玉市', updated_at = NOW() WHERE region_name = '昆玉市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/昌吉', updated_at = NOW() WHERE region_name = '昌吉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/昌江', updated_at = NOW() WHERE region_name = '昌江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/昌都', updated_at = NOW() WHERE region_name = '昌都' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/昭通', updated_at = NOW() WHERE region_name = '昭通' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/晋中', updated_at = NOW() WHERE region_name = '晋中' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/晋城', updated_at = NOW() WHERE region_name = '晋城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/普洱', updated_at = NOW() WHERE region_name = '普洱' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/景德镇', updated_at = NOW() WHERE region_name = '景德镇' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/智利', updated_at = NOW() WHERE region_name = '智利' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/曲靖', updated_at = NOW() WHERE region_name = '曲靖' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/朔州', updated_at = NOW() WHERE region_name = '朔州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/朝阳', updated_at = NOW() WHERE region_name = '朝阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/本溪', updated_at = NOW() WHERE region_name = '本溪' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/来宾', updated_at = NOW() WHERE region_name = '来宾' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/杭州', updated_at = NOW() WHERE region_name = '杭州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/松原', updated_at = NOW() WHERE region_name = '松原' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/林芝', updated_at = NOW() WHERE region_name = '林芝' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/果洛', updated_at = NOW() WHERE region_name = '果洛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/枣庄', updated_at = NOW() WHERE region_name = '枣庄' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/柬埔寨', updated_at = NOW() WHERE region_name = '柬埔寨' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/柳州', updated_at = NOW() WHERE region_name = '柳州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/株洲', updated_at = NOW() WHERE region_name = '株洲' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/桂林', updated_at = NOW() WHERE region_name = '桂林' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/梅州', updated_at = NOW() WHERE region_name = '梅州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/梧州', updated_at = NOW() WHERE region_name = '梧州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/楚雄', updated_at = NOW() WHERE region_name = '楚雄' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/榆林', updated_at = NOW() WHERE region_name = '榆林' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/武威', updated_at = NOW() WHERE region_name = '武威' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/武汉', updated_at = NOW() WHERE region_name = '武汉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/毕节', updated_at = NOW() WHERE region_name = '毕节' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/永州', updated_at = NOW() WHERE region_name = '永州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/汉中', updated_at = NOW() WHERE region_name = '汉中' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/汕头', updated_at = NOW() WHERE region_name = '汕头' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/汕尾', updated_at = NOW() WHERE region_name = '汕尾' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/江门', updated_at = NOW() WHERE region_name = '江门' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/池州', updated_at = NOW() WHERE region_name = '池州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/沈阳', updated_at = NOW() WHERE region_name = '沈阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/沙特阿拉伯', updated_at = NOW() WHERE region_name = '沙特阿拉伯' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/沧州', updated_at = NOW() WHERE region_name = '沧州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/河池', updated_at = NOW() WHERE region_name = '河池' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/河源', updated_at = NOW() WHERE region_name = '河源' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/泉州', updated_at = NOW() WHERE region_name = '泉州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/泰国', updated_at = NOW() WHERE region_name = '泰国' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/泰安', updated_at = NOW() WHERE region_name = '泰安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/泰州', updated_at = NOW() WHERE region_name = '泰州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/泸州', updated_at = NOW() WHERE region_name = '泸州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/洛阳', updated_at = NOW() WHERE region_name = '洛阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/津巴布韦', updated_at = NOW() WHERE region_name = '津巴布韦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/济南', updated_at = NOW() WHERE region_name = '济南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/济宁', updated_at = NOW() WHERE region_name = '济宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/济源市', updated_at = NOW() WHERE region_name = '济源市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/浙江', updated_at = NOW() WHERE region_name = '浙江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/海东', updated_at = NOW() WHERE region_name = '海东' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/海北', updated_at = NOW() WHERE region_name = '海北' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/海南州', updated_at = NOW() WHERE region_name = '海南州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/海口', updated_at = NOW() WHERE region_name = '海口' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/海西', updated_at = NOW() WHERE region_name = '海西' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/淄博', updated_at = NOW() WHERE region_name = '淄博' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/淮北', updated_at = NOW() WHERE region_name = '淮北' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/淮南', updated_at = NOW() WHERE region_name = '淮南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/淮安', updated_at = NOW() WHERE region_name = '淮安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/深圳', updated_at = NOW() WHERE region_name = '深圳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/清远', updated_at = NOW() WHERE region_name = '清远' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/温州', updated_at = NOW() WHERE region_name = '温州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/渭南', updated_at = NOW() WHERE region_name = '渭南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/湖南', updated_at = NOW() WHERE region_name = '湖南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/湖州', updated_at = NOW() WHERE region_name = '湖州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/湘潭', updated_at = NOW() WHERE region_name = '湘潭' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/湘西', updated_at = NOW() WHERE region_name = '湘西' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/湛江', updated_at = NOW() WHERE region_name = '湛江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/滁州', updated_at = NOW() WHERE region_name = '滁州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/滨州', updated_at = NOW() WHERE region_name = '滨州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/漯河', updated_at = NOW() WHERE region_name = '漯河' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/漳州', updated_at = NOW() WHERE region_name = '漳州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/潍坊', updated_at = NOW() WHERE region_name = '潍坊' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/潜江市', updated_at = NOW() WHERE region_name = '潜江市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/潮州', updated_at = NOW() WHERE region_name = '潮州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/澄迈', updated_at = NOW() WHERE region_name = '澄迈' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-MO', full_name = '港澳台/澳门特别行政区/澳门', updated_at = NOW() WHERE region_name = '澳门' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/濮阳', updated_at = NOW() WHERE region_name = '濮阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/烟台', updated_at = NOW() WHERE region_name = '烟台' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/焦作', updated_at = NOW() WHERE region_name = '焦作' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/牡丹江', updated_at = NOW() WHERE region_name = '牡丹江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/玉林', updated_at = NOW() WHERE region_name = '玉林' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/玉树', updated_at = NOW() WHERE region_name = '玉树' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/玉溪', updated_at = NOW() WHERE region_name = '玉溪' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/珠海', updated_at = NOW() WHERE region_name = '珠海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/琼中', updated_at = NOW() WHERE region_name = '琼中' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/琼海', updated_at = NOW() WHERE region_name = '琼海' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/瓦努阿图', updated_at = NOW() WHERE region_name = '瓦努阿图' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/甘南', updated_at = NOW() WHERE region_name = '甘南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/甘孜', updated_at = NOW() WHERE region_name = '甘孜' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/白城', updated_at = NOW() WHERE region_name = '白城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/白山', updated_at = NOW() WHERE region_name = '白山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/白沙', updated_at = NOW() WHERE region_name = '白沙' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/白银', updated_at = NOW() WHERE region_name = '白银' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/百色', updated_at = NOW() WHERE region_name = '百色' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/益阳', updated_at = NOW() WHERE region_name = '益阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/盐城', updated_at = NOW() WHERE region_name = '盐城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/盘锦', updated_at = NOW() WHERE region_name = '盘锦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/眉山', updated_at = NOW() WHERE region_name = '眉山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NX', full_name = '西北/宁夏回族自治区/石嘴山', updated_at = NOW() WHERE region_name = '石嘴山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/石家庄', updated_at = NOW() WHERE region_name = '石家庄' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/石河子市', updated_at = NOW() WHERE region_name = '石河子市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/神农架林区', updated_at = NOW() WHERE region_name = '神农架林区' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/福州', updated_at = NOW() WHERE region_name = '福州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/科特迪瓦', updated_at = NOW() WHERE region_name = '科特迪瓦' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/秘鲁', updated_at = NOW() WHERE region_name = '秘鲁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/秦皇岛', updated_at = NOW() WHERE region_name = '秦皇岛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/红河', updated_at = NOW() WHERE region_name = '红河' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/纳米比亚', updated_at = NOW() WHERE region_name = '纳米比亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/绍兴', updated_at = NOW() WHERE region_name = '绍兴' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/绥化', updated_at = NOW() WHERE region_name = '绥化' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/绵阳', updated_at = NOW() WHERE region_name = '绵阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/罗马尼亚', updated_at = NOW() WHERE region_name = '罗马尼亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/老挝', updated_at = NOW() WHERE region_name = '老挝' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/聊城', updated_at = NOW() WHERE region_name = '聊城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/肇庆', updated_at = NOW() WHERE region_name = '肇庆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/肯尼亚', updated_at = NOW() WHERE region_name = '肯尼亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/自贡', updated_at = NOW() WHERE region_name = '自贡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/舟山', updated_at = NOW() WHERE region_name = '舟山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/芜湖', updated_at = NOW() WHERE region_name = '芜湖' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/苏州', updated_at = NOW() WHERE region_name = '苏州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/茂名', updated_at = NOW() WHERE region_name = '茂名' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/荆州', updated_at = NOW() WHERE region_name = '荆州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/荆门', updated_at = NOW() WHERE region_name = '荆门' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/莆田', updated_at = NOW() WHERE region_name = '莆田' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/莫桑比克', updated_at = NOW() WHERE region_name = '莫桑比克' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/菏泽', updated_at = NOW() WHERE region_name = '菏泽' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/菲律宾', updated_at = NOW() WHERE region_name = '菲律宾' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/萍乡', updated_at = NOW() WHERE region_name = '萍乡' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/营口', updated_at = NOW() WHERE region_name = '营口' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/葫芦岛', updated_at = NOW() WHERE region_name = '葫芦岛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/蚌埠', updated_at = NOW() WHERE region_name = '蚌埠' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/衡水', updated_at = NOW() WHERE region_name = '衡水' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/衡阳', updated_at = NOW() WHERE region_name = '衡阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/衢州', updated_at = NOW() WHERE region_name = '衢州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/襄阳', updated_at = NOW() WHERE region_name = '襄阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/西双版纳', updated_at = NOW() WHERE region_name = '西双版纳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/西咸新区', updated_at = NOW() WHERE region_name = '西咸新区' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/西宁', updated_at = NOW() WHERE region_name = '西宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/西安', updated_at = NOW() WHERE region_name = '西安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/许昌', updated_at = NOW() WHERE region_name = '许昌' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/贝宁', updated_at = NOW() WHERE region_name = '贝宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/贵港', updated_at = NOW() WHERE region_name = '贵港' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/贵阳', updated_at = NOW() WHERE region_name = '贵阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/贺州', updated_at = NOW() WHERE region_name = '贺州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/资阳', updated_at = NOW() WHERE region_name = '资阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/赞比亚', updated_at = NOW() WHERE region_name = '赞比亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/赣州', updated_at = NOW() WHERE region_name = '赣州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/赤峰', updated_at = NOW() WHERE region_name = '赤峰' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/越南', updated_at = NOW() WHERE region_name = '越南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/辽源', updated_at = NOW() WHERE region_name = '辽源' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/辽阳', updated_at = NOW() WHERE region_name = '辽阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/达州', updated_at = NOW() WHERE region_name = '达州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/运城', updated_at = NOW() WHERE region_name = '运城' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/连云港', updated_at = NOW() WHERE region_name = '连云港' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-YN', full_name = '西南/云南省/迪庆', updated_at = NOW() WHERE region_name = '迪庆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/通化', updated_at = NOW() WHERE region_name = '通化' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/通辽', updated_at = NOW() WHERE region_name = '通辽' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/遂宁', updated_at = NOW() WHERE region_name = '遂宁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/遵义', updated_at = NOW() WHERE region_name = '遵义' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/邢台', updated_at = NOW() WHERE region_name = '邢台' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/那曲', updated_at = NOW() WHERE region_name = '那曲' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HE', full_name = '华北/河北省/邯郸', updated_at = NOW() WHERE region_name = '邯郸' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/邵阳', updated_at = NOW() WHERE region_name = '邵阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/郑州', updated_at = NOW() WHERE region_name = '郑州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/郴州', updated_at = NOW() WHERE region_name = '郴州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/鄂尔多斯', updated_at = NOW() WHERE region_name = '鄂尔多斯' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/鄂州', updated_at = NOW() WHERE region_name = '鄂州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/酒泉', updated_at = NOW() WHERE region_name = '酒泉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-CQ', full_name = '西南/重庆/重庆', updated_at = NOW() WHERE region_name = '重庆' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-ZJ', full_name = '华东/浙江省/金华', updated_at = NOW() WHERE region_name = '金华' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/金昌', updated_at = NOW() WHERE region_name = '金昌' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/钦州', updated_at = NOW() WHERE region_name = '钦州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/铁岭', updated_at = NOW() WHERE region_name = '铁岭' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/铁门关市', updated_at = NOW() WHERE region_name = '铁门关市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/铜仁', updated_at = NOW() WHERE region_name = '铜仁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SN', full_name = '西北/陕西省/铜川', updated_at = NOW() WHERE region_name = '铜川' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/铜陵', updated_at = NOW() WHERE region_name = '铜陵' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NX', full_name = '西北/宁夏回族自治区/银川', updated_at = NOW() WHERE region_name = '银川' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/锡林郭勒盟', updated_at = NOW() WHERE region_name = '锡林郭勒盟' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/锦州', updated_at = NOW() WHERE region_name = '锦州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JS', full_name = '华东/江苏省/镇江', updated_at = NOW() WHERE region_name = '镇江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JL', full_name = '东北/吉林省/长春', updated_at = NOW() WHERE region_name = '长春' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HN', full_name = '华中/湖南省/长沙', updated_at = NOW() WHERE region_name = '长沙' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/长治', updated_at = NOW() WHERE region_name = '长治' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/阜新', updated_at = NOW() WHERE region_name = '阜新' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/阜阳', updated_at = NOW() WHERE region_name = '阜阳' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GX', full_name = '华南/广西壮族自治区/防城港', updated_at = NOW() WHERE region_name = '防城港' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/阳江', updated_at = NOW() WHERE region_name = '阳江' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SX', full_name = '华北/山西省/阳泉', updated_at = NOW() WHERE region_name = '阳泉' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/阿克苏', updated_at = NOW() WHERE region_name = '阿克苏' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/阿勒泰', updated_at = NOW() WHERE region_name = '阿勒泰' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/阿坝', updated_at = NOW() WHERE region_name = '阿坝' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/阿富汗', updated_at = NOW() WHERE region_name = '阿富汗' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/阿尔及利亚', updated_at = NOW() WHERE region_name = '阿尔及利亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-NM', full_name = '华北/内蒙古自治区/阿拉善盟', updated_at = NOW() WHERE region_name = '阿拉善盟' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XJ', full_name = '西北/新疆维吾尔自治区/阿拉尔市', updated_at = NOW() WHERE region_name = '阿拉尔市' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/阿曼', updated_at = NOW() WHERE region_name = '阿曼' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/阿联酋', updated_at = NOW() WHERE region_name = '阿联酋' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-XZ', full_name = '西南/西藏自治区/阿里', updated_at = NOW() WHERE region_name = '阿里' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GS', full_name = '西北/甘肃省/陇南', updated_at = NOW() WHERE region_name = '陇南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HI', full_name = '华南/海南省/陵水', updated_at = NOW() WHERE region_name = '陵水' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/随州', updated_at = NOW() WHERE region_name = '随州' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SC', full_name = '西南/四川省/雅安', updated_at = NOW() WHERE region_name = '雅安' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-SD', full_name = '华东/山东省/青岛', updated_at = NOW() WHERE region_name = '青岛' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-LN', full_name = '东北/辽宁省/鞍山', updated_at = NOW() WHERE region_name = '鞍山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GD', full_name = '华南/广东省/韶关', updated_at = NOW() WHERE region_name = '韶关' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HK', full_name = '港澳台/香港特别行政区/香港', updated_at = NOW() WHERE region_name = '香港' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/马拉维', updated_at = NOW() WHERE region_name = '马拉维' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/马来西亚', updated_at = NOW() WHERE region_name = '马来西亚' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/马鞍山', updated_at = NOW() WHERE region_name = '马鞍山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/驻马店', updated_at = NOW() WHERE region_name = '驻马店' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/鸡西', updated_at = NOW() WHERE region_name = '鸡西' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HA', full_name = '华中/河南省/鹤壁', updated_at = NOW() WHERE region_name = '鹤壁' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/鹤岗', updated_at = NOW() WHERE region_name = '鹤岗' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-JX', full_name = '华东/江西省/鹰潭', updated_at = NOW() WHERE region_name = '鹰潭' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/黄冈', updated_at = NOW() WHERE region_name = '黄冈' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-QH', full_name = '西北/青海省/黄南', updated_at = NOW() WHERE region_name = '黄南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-AH', full_name = '华东/安徽省/黄山', updated_at = NOW() WHERE region_name = '黄山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HB', full_name = '华中/湖北省/黄石', updated_at = NOW() WHERE region_name = '黄石' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-INTL', full_name = '海外/海外/黑山', updated_at = NOW() WHERE region_name = '黑山' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/黑河', updated_at = NOW() WHERE region_name = '黑河' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/黔东南', updated_at = NOW() WHERE region_name = '黔东南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/黔南', updated_at = NOW() WHERE region_name = '黔南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-GZ', full_name = '西南/贵州省/黔西南', updated_at = NOW() WHERE region_name = '黔西南' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-HLJ', full_name = '东北/黑龙江省/齐齐哈尔', updated_at = NOW() WHERE region_name = '齐齐哈尔' AND region_code LIKE 'CITY_%';
UPDATE dim_region SET region_level = 3, parent_code = 'CN-FJ', full_name = '华东/福建省/龙岩', updated_at = NOW() WHERE region_name = '龙岩' AND region_code LIKE 'CITY_%';

UPDATE biz_job_posting jp JOIN dim_region city ON city.region_code = jp.city_code LEFT JOIN dim_region province ON province.region_code = city.parent_code LEFT JOIN dim_region region ON region.region_code = province.parent_code SET jp.province_code = province.region_code,     jp.region_code = region.region_code,     jp.region = COALESCE(province.region_name, jp.region),     jp.city = COALESCE(city.region_name, jp.city),     jp.updated_at = NOW() WHERE jp.city_code IS NOT NULL;
UPDATE biz_company bc JOIN dim_region city ON city.region_code = bc.city_code LEFT JOIN dim_region province ON province.region_code = city.parent_code LEFT JOIN dim_region region ON region.region_code = province.parent_code SET bc.province_code = province.region_code,     bc.region_code = region.region_code,     bc.updated_at = NOW() WHERE bc.city_code IS NOT NULL;

SELECT COUNT(*) AS total, SUM(region_level = 1) AS level1_count, SUM(region_level = 2) AS level2_count, SUM(region_level = 3) AS level3_count, SUM(parent_code IS NULL) AS no_parent_count FROM dim_region;
SELECT (SELECT COUNT(*) FROM biz_job_posting WHERE city_code IS NOT NULL) AS jp_city, (SELECT COUNT(*) FROM biz_job_posting WHERE province_code IS NOT NULL) AS jp_province, (SELECT COUNT(*) FROM biz_job_posting WHERE region_code IS NOT NULL) AS jp_region, (SELECT COUNT(*) FROM biz_company WHERE city_code IS NOT NULL) AS company_city, (SELECT COUNT(*) FROM biz_company WHERE province_code IS NOT NULL) AS company_province, (SELECT COUNT(*) FROM biz_company WHERE region_code IS NOT NULL) AS company_region;
